In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import HTML

import importlib

import data_processing as d
# import visualize_robot_pov_plotly as v

importlib.reload(d)
# importlib.reload(v)

%matplotlib notebook
video_path = "./videos/c1.avi"

In [2]:
# extract face direction and yolo poses
results = d.load_video_get_features(video_path)


WARNING 
inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/1035) c:\Users\Tian_\Documents\School\Meng\AER 1515\Project\tian\videos\c1.avi: 480x640 2 persons, 92.2ms
video 1/1 (frame 2/1035) c:\Users\Tian_\Documents\School\Meng\AER 1515\Project\tian\videos\c1.avi: 480x640 2 persons, 80.3ms
video 1/1 (frame 3/1035) c:\Users\Tian_\Documents\School\Meng\AER 1515\Project\tian\videos\c1.avi: 480x640 2 persons, 59.1ms
video 1/1 (frame 4/1035) c:\Users\Tian_\Documents\School\Meng\AER 1515\Project\tian\

In [3]:
yolo_results = results[0]

k = np.array([
    [ 280, 0, 160],
    [0, -280, 120],
    [0, 0, 1]
    ])
# k = np.array([
#     [ 1, 0, 0],
#     [0, -1, 0],
#     [0, 0, 1]
#     ])
# eyeballed based on formula (w/2)/tan(fov/2) camera focal length from fov and sensor size

yolo_proc_out = d.process_yolo_output(yolo_results, k)
print(yolo_proc_out.shape)
ani = d.draw_points_matplot(yolo_proc_out, use_array = True, only_2d = True)
# display(HTML(ani.to_jshtml()))
d.draw_features(video_path, yolo_results)

(3, 2941)
[[     166.25      166.32      169.24 ...      154.23      165.77      167.79]
 [     79.555      75.571      75.072 ...       209.8         240      234.27]
 [          1           1           1 ...           1           1           1]]
(173, 17, 2)


<IPython.core.display.Javascript object>

(17, 173)
no frame returned


In [ ]:
# format extracted data
# yolo poses into normalized frame in form [1, y, z]